# Generated by Django 3.2.6 on 2021-09-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ChuyenDaLai',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='DoThanThiet',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='SoVeDaDat',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ThuViec',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
