# Generated by Django 3.2.6 on 2021-08-19 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeBaoTri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiDiem', models.DateField(auto_now_add=True)),
                ('Xe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.xe')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiDiem', models.DateField()),
                ('NhanVienBanVe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.nhanvienbanve')),
                ('TaiXe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.taixe')),
            ],
        ),
    ]
