# Generated by Django 3.2.6 on 2021-08-19 15:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0002_chitieu_xebaotri'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chitieu',
            options={'verbose_name_plural': 'Chi tiêu'},
        ),
        migrations.AlterModelOptions(
            name='xebaotri',
            options={'verbose_name_plural': 'Xe bảo trì'},
        ),
        migrations.AlterField(
            model_name='danhgia',
            name='NoiDung',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
