# Generated by Django 3.2.6 on 2021-08-20 09:12

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0003_auto_20210819_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='danhgia',
            options={'verbose_name_plural': 'Đánh giá'},
        ),
        migrations.AlterField(
            model_name='danhgia',
            name='NoiDung',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='tuyen',
            name='NoiDen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuyen_den', to='quanly.benxe'),
        ),
        migrations.AlterField(
            model_name='tuyen',
            name='NoiKhoiHanh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuyen_khoi_hanh', to='quanly.benxe'),
        ),
    ]
